# Assignment 1 – Variables, Numbers, and Strings
**Course:** Python for Data Science (Codebasics)  
**Status:** ✅ Completed  
**Date:** July 19, 2025

This notebook covers the basics of Python including:
- Variable assignment
- Number types and operations
- Strings and common string functions


### Task 1

Create a variable named pi and store the value 22/7 in it. Now check the data type of this variable.

In [1]:
pi=22/7
print(type(pi))


<class 'float'>


### Task 2

Create a variable called ```for``` and assign it a value 4. See what happens and find out the reason behind the behavior that you see.

In [3]:
for=4
#for the reserved words like for we cannot assign the value


SyntaxError: invalid syntax (2450915575.py, line 1)

### Task 3

Below we have defined the variables for storing the principal amount, rate of interest and time. You need to calculate the simple interest for 3 years. Once simple interest is calculated, calculate the total amount you will have at the end of the tenure

In [14]:
principle_amount = 567.00
rate_of_interest = 5.6
time = 3


95.25599999999999


Now let's calculate the simple intrest using simple math formula:

`simple interest  = P x R x T / 100`

where: 
 
    P = principle amount
    R = rate of interest
    T = time 



In [15]:
simple_interest= principle_amount * rate_of_interest * time/ 100
print(simple_interest)


95.25599999999999


In [16]:
total_amount=principle_amount+simple_interest
print(total_amount)


662.256


### Task 4

There is a circular pond in a village. This pond has a radius of 84 meter. Can you find the area of the pond?

In [20]:
pi=22/7
radius=84
area=pi* radius**2
print(area)

22176.0


### Task 5

If there is a 2000 liter water in a square meter, what is the total amount of water in this pond?

**Note:** For simplicity, use the value of pi as 3.14.

In [22]:
per_sqr_mtr_water=2000
total_water=per_sqr_mtr_water*area
print(total_water)


44352000.0


### Task 6

If you cross a 490-meter-long street in 7 minutes, then what is your speed in meter per seconds. Print your answer with only two decimal points

Hint:
        Speed = Distance / Time

In [28]:
distance=490
time_in_sec=7*60
speed=distance/time_in_sec
print(round(speed,2))



1.17


### Task 7

Create two variables to store how many fruits and vegetables you eat in a day. The value should be numeric for example 3 fruits and 4 vegetables. Now Print "I eat x vegetables and y fruits daily" where x and y presents vegetables and fruits that you eat every day. Use python f string for this.

In [31]:
x_vegetable=4 
y_fruits=5
print(f"I eat {x_vegetable} vegetables and {y_fruits} fruits daily")


I eat 4 vegetables and 5 fruits daily


### Task 8

Create a variable and store the string “The Himalayas are one of the youngest mountain range on the planet.”

1. Print ‘The Himalayas’ using slice operator
1. Print “mountain range” using negative index
1. Print “The Himalayas on the planet” using slice as well as f-string

In [39]:
# write your code here
string="The Himalayas are one of the youngest mountain range on the planet."
print(string[0:13])
print(string[-29:-15])
print(f"{string[0:13]} {string[-14:]}")


The Himalayas
mountain range
The Himalayas on the planet.


### Task 9

You have created a string variable called string= ”There are 9 planets in the solar system”. After some time, you have realized that your sentence is incorrect and there are only 8 planets, now correct your sentence by replacing the incorrect words.

In [41]:
string="There are 9 planets in the solar system"
print(string)
result=string.replace('9','8')
print(result)




There are 9 planets in the solar system
There are 8 planets in the solar system


In [44]:
# Prices and quantities for each product
product1_price = 20.0  # Price per unit for product 1
product1_quantity = 15  # Quantity sold of product 1

product2_price = 35.0  # Price per unit for product 2
product2_quantity = 10  # Quantity sold of product 2

product3_price = 12.0  # Price per unit for product 3
product3_quantity = 20  # Quantity sold of product 3



Product 1: Sold 15 units at $20.0 each, Total: $300.0


### Task 10

Imagine you are a shop owner tracking sales of three products throughout the day. At the end of the day, you want to calculate the total sales from these products. Product quantity and prices are given below in the next code cell,

Task: Write a program that:

1. Calculates the total sales for each product.
1. Summarizes the total sales for the day.
1. Prints this summary in a formatted manner.

Expected Output:

```
Daily Sales Summary:
- Product 1: Sold 15 units at $20.0 each, Total: $300.0
- Product 2: Sold 10 units at $35.0 each, Total: $350.0
- Product 3: Sold 20 units at $12.0 each, Total: $240.0
Total Sales for the Day: $890.0
```

In [48]:
total_1=product1_price*product1_quantity
total_2=product2_price*product2_quantity
total_3=product3_price*product3_quantity
total_sales=total_1+total_2+total_3
print(f"Product 1: Sold {product1_quantity} units at ${product1_price} each, Total: ${total_1}")
print(f"Product 2: Sold {product2_quantity} units at ${product2_price} each, Total: ${total_2}")
print(f"Product 3: Sold {product3_quantity} units at ${product3_price} each, Total: ${total_3}")
print(f"Total sales of the day is {total_sales}")

Product 1: Sold 15 units at $20.0 each, Total: $300.0
Product 2: Sold 10 units at $35.0 each, Total: $350.0
Product 3: Sold 20 units at $12.0 each, Total: $240.0
Total sales of the day is 890.0




✅ **Assignment Completed Successfully**

🧠 Skills Practiced:
- Variable assignment
- Arithmetic operations
- String slicing and formatting
- Type checking

🚀 Ready to move to the next module!
